### ISSUE TITLE
enhancement - resize image on callback

### ISSUE THREAD

**Issue by johndpope** [mcmatan/JVTImageFilePicker#4]
UIImage+Resize

https://github.com/coryalder/UIImage_Resize/blob/Standalone/UIImage%2BResize.h

Background - 
I am using a similar method in another imagepicker library.
It helps me reduce file sizes when uploading image picked.
Your image picker is used so much through app - it becomes a bit of a pain to wrap. 
Ideally - I want to specify width / height for image to be resized.
I tried subclassing - but the actionsheet is private.

@interface NewImagePickerController :JVTImageFilePicker
@property(nonatomic, assign) CGFloat width;
@property(nonatomic, assign) CGRect rect;
@property(nonatomic, assign) BOOL resize;
@property(nonatomic, assign) UIViewController *delegate;
@end

- (void) resizeImageInBackground:(UIImage *)originalImage {
    @autoreleasepool {
        NSLog(@"resizeImageInBackground");
        @try {
            if (self.width > 0) {
                CGSize size = CGSizeMake(self.width, self.width * originalImage.size.height / originalImage.size.width);
                NSLog(@"Original: %f,%f Resized: %f,%f", originalImage.size.width, originalImage.size.height, size.width, size.height);
                UIImage *resizedImage = [originalImage resizedImage:size interpolationQuality:kCGInterpolationHigh];
                if (resizedImage != nil) {
                    [self dispatchSelector:@selector(imagePickerDidFinish:image:)
                                    target:self.delegate
                                   objects:self, resizedImage, nil];
                }
                else {
                    [self dispatchSelector:@selector(imagePickerDidFinish:image:)
                                    target:self.delegate
                                   objects:self, originalImage, nil];
                }
            }
            else {
                [self dispatchSelector:@selector(imagePickerDidFinish:image:)
                                target:self.delegate 
                               objects:self, originalImage, nil];
            }
        }
        @catch (NSException *e) {
            NSLog(@"NSException: %@", e);
            [self dispatchSelector:@selector(imagePickerDidFinish:image:) 
                            target:self.delegate 
                           objects:self, originalImage, nil];
        }
    }
}

**Comment by mcmatan** [comment]
Thank you for your feedback, I've added an option to set your own ImageSize, just change the property like so:

self.imageFilesPicker.imageResizeSize = CGSizeMake(100, 100);

Hope it helps (:
