### ISSUE TITLE
ios 10 crash - after authorizing camera - LLSimpleCamera.h xcode 8.1

### ISSUE THREAD

**Issue by johndpope** [mcmatan/JVTImageFilePicker#7]
<img width="1155" alt="screen shot 2016-12-07 at 6 38 45 am" src="https://cloud.githubusercontent.com/assets/289994/20940698/d3630672-bc47-11e6-9253-17f5a9acf77a.png">

it might be better to extend dependency on this https://github.com/omergul123/LLSimpleCamera/blob/master/LLSimpleCamera.podspec

<img width="1135" alt="screen shot 2016-12-07 at 6 42 21 am" src="https://cloud.githubusercontent.com/assets/289994/20940857/58874304-bc48-11e6-8a62-52ae7022ec84.png">

I can confirm this is blowing up with sample project too. 

I tried the solutions here - doesn't seem to help. 
http://stackoverflow.com/questions/38267608/requestaccessformediatype-crashing-in-ios-10

**Comment by mcmatan** [comment]
Hi, thanks for the issue, can you give me more details? which IOS 10 is it? 10.1, 10.2? 
And was it on which device? I'm trying to reproduce, thanks

**Comment by johndpope** [comment]
this code fixes it.
https://github.com/mcmatan/JVTImageFilePicker/commit/4e558cbe6561f5210ffb549dfcc65bb240510aae
just need to bump pod version.

**Comment by mcmatan** [comment]
Perfect (:
